#!/usr/bin/env bun

import path from "node:path";

import { BunRuntime } from "@effect/platform-bun";
import { Console, Effect, Schema } from "effect";

import { createHomebrewCaskDefinition, renderValidatedHomebrewCask } from "../src/homebrewCask.ts";
import type { ServiceChecksum } from "../src/serviceBuild.ts";

/** Parsed command-line options for the Homebrew cask writer. */
interface ParsedWriteHomebrewCaskArgs {
  readonly checksumsPath: string;
  readonly outputPath: string;
  readonly repository: string;
  readonly version: string;
}

/** Failure while writing the generated Homebrew cask. */
class WriteHomebrewCaskError extends Schema.TaggedErrorClass<WriteHomebrewCaskError>()(
  "WriteHomebrewCaskError",
  {
    message: Schema.String,
  },
) {}

/** Builds one cask writer failure. */
const writeHomebrewCaskError = ({
  message,
}: {
  readonly message: string;
}): WriteHomebrewCaskError => new WriteHomebrewCaskError({ message });

/** Reads the next separated CLI value or fails with a specific missing-value error. */
const separatedValue = Effect.fnUntraced(function* ({
  args,
  index,
  optionName,
}: {
  readonly args: readonly string[];
  readonly index: number;
  readonly optionName: string;
}) {
  const value = args[index + 1];
  if (value === undefined || value.startsWith("--")) {
    return yield* writeHomebrewCaskError({ message: `${optionName} requires a value.` });
  }
  return value;
});

/** Parses cask writer command-line arguments. */
const parseWriteHomebrewCaskArgs = Effect.fnUntraced(function* ({
  args,
}: {
  readonly args: readonly string[];
}) {
  let checksumsPath: string | undefined;
  let outputPath: string | undefined;
  let repository: string | undefined;
  let version: string | undefined;
  let index = 0;

  while (index < args.length) {
    const arg = args[index];
    if (arg === "--checksums") {
      checksumsPath = yield* separatedValue({ args, index, optionName: "--checksums" });
      index += 2;
    } else if (arg === "--output") {
      outputPath = yield* separatedValue({ args, index, optionName: "--output" });
      index += 2;
    } else if (arg === "--repository") {
      repository = yield* separatedValue({ args, index, optionName: "--repository" });
      index += 2;
    } else if (arg === "--version") {
      version = yield* separatedValue({ args, index, optionName: "--version" });
      index += 2;
    } else {
      return yield* writeHomebrewCaskError({
        message: `Unsupported Homebrew cask writer option: ${arg ?? "<missing>"}.`,
      });
    }
  }

  if (checksumsPath === undefined) {
    return yield* writeHomebrewCaskError({ message: "--checksums requires a value." });
  }
  if (outputPath === undefined) {
    return yield* writeHomebrewCaskError({ message: "--output requires a value." });
  }
  if (repository === undefined) {
    return yield* writeHomebrewCaskError({ message: "--repository requires a value." });
  }
  if (version === undefined) {
    return yield* writeHomebrewCaskError({ message: "--version requires a value." });
  }

  return {
    checksumsPath,
    outputPath,
    repository,
    version,
  } satisfies ParsedWriteHomebrewCaskArgs;
});

/** Parses one sha256sum-style checksum line. */
const parseChecksumLine = Effect.fnUntraced(function* ({ line }: { readonly line: string }) {
  const match = /^([a-f0-9]{64})\s+(.+)$/u.exec(line);
  if (match === null) {
    return yield* writeHomebrewCaskError({ message: `Invalid checksum line: ${line}` });
  }
  const sha256 = match.at(1);
  const artifactName = match.at(2);
  if (sha256 === undefined || artifactName === undefined) {
    return yield* writeHomebrewCaskError({ message: `Invalid checksum line: ${line}` });
  }
  return {
    path: artifactName,
    sha256,
  } satisfies ServiceChecksum;
});

/** Reads and parses the checksum manifest generated by the service build script. */
const readChecksums = Effect.fnUntraced(function* ({
  checksumsPath,
}: {
  readonly checksumsPath: string;
}) {
  const text = yield* Effect.tryPromise({
    try: () => Bun.file(checksumsPath).text(),
    catch: () =>
      writeHomebrewCaskError({ message: `Failed to read checksums file: ${checksumsPath}.` }),
  });
  return yield* Effect.forEach(
    text.split("\n").filter((line) => line.length > 0),
    (line) => parseChecksumLine({ line }),
    { concurrency: 1 },
  );
});

/** Writes generated cask text to the requested output path. */
const writeCaskText = Effect.fnUntraced(function* ({
  caskText,
  outputPath,
}: {
  readonly caskText: string;
  readonly outputPath: string;
}) {
  yield* Effect.tryPromise({
    try: () => Bun.write(outputPath, caskText),
    catch: () => writeHomebrewCaskError({ message: `Failed to write ${outputPath}.` }),
  });
  yield* Console.log(`Wrote ${path.normalize(outputPath)}`);
});

/** Parses args, renders the cask, validates it, and writes it to disk. */
const runWriteHomebrewCaskCli = Effect.fnUntraced(function* ({
  args,
}: {
  readonly args: readonly string[];
}) {
  const parsed = yield* parseWriteHomebrewCaskArgs({ args });
  const checksums = yield* readChecksums({ checksumsPath: parsed.checksumsPath });
  const definition = yield* createHomebrewCaskDefinition({
    checksums,
    repository: parsed.repository,
    version: parsed.version,
  });
  const caskText = yield* renderValidatedHomebrewCask({ definition });
  yield* writeCaskText({ caskText, outputPath: parsed.outputPath });
});

/** Runs the Homebrew cask writer script. */
BunRuntime.runMain(runWriteHomebrewCaskCli({ args: process.argv.slice(2) }));
