import fs from "node:fs/promises";
import path from "node:path";

import { Effect, Match } from "effect";

import { caaraCodexRoleInstallerError } from "./codexRoleInstallerError.ts";
import { pathExists } from "./fsPathExists.ts";

/** Returns the marker opening the Caara-managed block inside the global Codex AGENTS.md. */
export const codexAgentsGuidanceBeginMarker = (): string => "<!-- caara:agents:begin -->";

/** Returns the marker closing the Caara-managed block inside the global Codex AGENTS.md. */
export const codexAgentsGuidanceEndMarker = (): string => "<!-- caara:agents:end -->";

/** Options selecting the rendered guidance content. */
export interface RenderCodexAgentsGuidanceBlockOptions {
  readonly panelSkillInstalled: boolean;
}

/** Result of computing the next guidance document content. */
export type CodexAgentsGuidanceUpdate =
  | {
      readonly _tag: "Write";
      readonly content: string;
    }
  | {
      readonly _tag: "Delete";
    }
  | {
      readonly _tag: "Unchanged";
    }
  | {
      readonly _tag: "Corrupt";
      readonly reason: string;
    };

/** Portable blind-delegation workflow installed for Codex orchestrators. */
const crossModelParagraph = [
  "Use Caara's portable CLI for blind delegation to a different model family. This workflow does",
  "not depend on Codex subagent roles or native subagent tool schemas.",
  "",
  "1. Select an explicit target such as `claude/sonnet` or `agy/gemini-3.5-flash` and an absolute",
  "   working directory. Put arbitrary or multiline task text in a file; do not interpolate it into",
  "   shell syntax.",
  "2. Run `caara agent start --json --target TARGET --cwd CWD --prompt-file PROMPT_FILE`.",
  "   Accepted starts exit 10. Parse the JSON; immediately show `observationUrl` to the user as a",
  "   clickable human-only link; never open, fetch, inspect, or summarize that URL, and never pass it",
  "   to another tool or model. It is a bearer capability containing private agent activity.",
  "3. Repeatedly run `caara agent wait --json --timeout-millis 30000 TURN_ID`. Exit 11 means the",
  "   turn is still working; wait again without reading the observation page. On completion, consume",
  "   only `finalAnswer` from the terminal JSON. Do not seek reasoning, tool activity, or transcripts.",
  "4. If the task must stop, run `caara agent cancel --json TURN_ID`. Successful cancellation exits",
  "   12; honor `sessionReusable` before attempting any follow-up with `--session-id`.",
].join("\n");

/** Guidance paragraph pointing at the globally installed panel skill. */
const panelParagraph = [
  "For structured multi-model work — ensemble attempts, debates, cross-review — invoke the global",
  "`$panel` skill.",
].join("\n");

/** Renders the full marked guidance block for the global Codex AGENTS.md. */
export const renderCodexAgentsGuidanceBlock = ({
  panelSkillInstalled,
}: RenderCodexAgentsGuidanceBlockOptions): string =>
  [
    codexAgentsGuidanceBeginMarker(),
    "<!-- Generated by Caara. Content between the caara:agents markers is overwritten on reinstall. -->",
    "",
    "## Cross-model subagents (Caara)",
    "",
    crossModelParagraph,
    ...["", panelParagraph].filter(() => panelSkillInstalled),
    "",
    codexAgentsGuidanceEndMarker(),
  ].join("\n");

/** Located marker span inside one guidance document. */
type MarkerSpan =
  | {
      readonly _tag: "Absent";
    }
  | {
      readonly _tag: "Present";
      readonly beginIndex: number;
      readonly endIndex: number;
    }
  | {
      readonly _tag: "Corrupt";
      readonly reason: string;
    };

/** Locates the managed marker span inside one guidance document. */
const locateMarkerSpan = ({ source }: { readonly source: string }): MarkerSpan => {
  const beginIndex = source.indexOf(codexAgentsGuidanceBeginMarker());
  const endIndex = source.indexOf(codexAgentsGuidanceEndMarker());
  const duplicated =
    beginIndex !== source.lastIndexOf(codexAgentsGuidanceBeginMarker()) ||
    endIndex !== source.lastIndexOf(codexAgentsGuidanceEndMarker());
  return Match.value({
    duplicated,
    hasBegin: beginIndex !== -1,
    hasEnd: endIndex !== -1,
    ordered: endIndex > beginIndex,
  }).pipe(
    Match.when({ hasBegin: false, hasEnd: false }, () => ({ _tag: "Absent" }) satisfies MarkerSpan),
    Match.when(
      { duplicated: true },
      () =>
        ({
          _tag: "Corrupt",
          reason: "multiple caara:agents marker pairs are present",
        }) satisfies MarkerSpan,
    ),
    Match.when(
      { hasBegin: true, hasEnd: true, ordered: true },
      () => ({ _tag: "Present", beginIndex, endIndex }) satisfies MarkerSpan,
    ),
    Match.when(
      { hasBegin: true, hasEnd: true, ordered: false },
      () =>
        ({
          _tag: "Corrupt",
          reason: "the caara:agents end marker precedes the begin marker",
        }) satisfies MarkerSpan,
    ),
    Match.orElse(
      () =>
        ({
          _tag: "Corrupt",
          reason: "only one caara:agents marker is present",
        }) satisfies MarkerSpan,
    ),
  );
};

/** Joins document fragments while normalizing the blank line between them. */
const joinDocumentParts = (parts: readonly string[]): string =>
  parts.filter((part) => part.trim().length > 0).join("\n\n");

/** Computes the next guidance document content with the managed block inserted or replaced. */
export const upsertCodexAgentsGuidance = ({
  block,
  source,
}: {
  readonly block: string;
  readonly source: string | undefined;
}): CodexAgentsGuidanceUpdate =>
  Match.value(locateMarkerSpan({ source: source ?? "" })).pipe(
    Match.tag(
      "Absent",
      () =>
        ({
          _tag: "Write",
          content: `${joinDocumentParts([(source ?? "").trimEnd(), block])}\n`,
        }) satisfies CodexAgentsGuidanceUpdate,
    ),
    Match.tag("Present", ({ beginIndex, endIndex }) => {
      const existing = source ?? "";
      const prefix = existing.slice(0, beginIndex);
      const suffix = existing.slice(endIndex + codexAgentsGuidanceEndMarker().length);
      return {
        _tag: "Write",
        content: `${joinDocumentParts([prefix.trimEnd(), block, suffix.trim()])}\n`,
      } satisfies CodexAgentsGuidanceUpdate;
    }),
    Match.tag(
      "Corrupt",
      ({ reason }) => ({ _tag: "Corrupt", reason }) satisfies CodexAgentsGuidanceUpdate,
    ),
    Match.exhaustive,
  );

/** Computes the removal outcome for one present marker span. */
const removalUpdateFromSpan = ({
  beginIndex,
  endIndex,
  source,
}: {
  readonly beginIndex: number;
  readonly endIndex: number;
  readonly source: string;
}): CodexAgentsGuidanceUpdate => {
  const prefix = source.slice(0, beginIndex);
  const suffix = source.slice(endIndex + codexAgentsGuidanceEndMarker().length);
  const remainder = joinDocumentParts([prefix.trimEnd(), suffix.trim()]);
  return Match.value(remainder.length).pipe(
    Match.when(0, () => ({ _tag: "Delete" }) satisfies CodexAgentsGuidanceUpdate),
    Match.orElse(
      () => ({ _tag: "Write", content: `${remainder}\n` }) satisfies CodexAgentsGuidanceUpdate,
    ),
  );
};

/** Computes the next guidance document content with the managed block removed. */
export const removeCodexAgentsGuidance = ({
  source,
}: {
  readonly source: string;
}): CodexAgentsGuidanceUpdate =>
  Match.value(locateMarkerSpan({ source })).pipe(
    Match.tag("Absent", () => ({ _tag: "Unchanged" }) satisfies CodexAgentsGuidanceUpdate),
    Match.tag("Present", ({ beginIndex, endIndex }) =>
      removalUpdateFromSpan({ beginIndex, endIndex, source }),
    ),
    Match.tag(
      "Corrupt",
      ({ reason }) => ({ _tag: "Corrupt", reason }) satisfies CodexAgentsGuidanceUpdate,
    ),
    Match.exhaustive,
  );

/** Reads one guidance document, mapping a missing file to undefined. */
const readGuidanceFile = Effect.fnUntraced(function* ({
  agentsFilePath,
}: {
  readonly agentsFilePath: string;
}) {
  const exists = yield* pathExists({ targetPath: agentsFilePath });
  const sources = yield* Effect.forEach(
    [agentsFilePath].filter(() => exists),
    (existingPath) =>
      Effect.tryPromise({
        try: () => fs.readFile(existingPath, "utf8"),
        catch: (cause) =>
          caaraCodexRoleInstallerError(
            `Failed to read Codex AGENTS.md at ${existingPath}: ${String(cause)}`,
          ),
      }),
    { concurrency: 1 },
  );
  return sources.at(0);
});

/** Writes one guidance document to disk, creating its parent directory first. */
const writeGuidanceContent = Effect.fnUntraced(function* ({
  agentsFilePath,
  content,
}: {
  readonly agentsFilePath: string;
  readonly content: string;
}) {
  yield* Effect.tryPromise({
    try: () => fs.mkdir(path.dirname(agentsFilePath), { recursive: true }),
    catch: (cause) =>
      caaraCodexRoleInstallerError(
        `Failed to create directory for Codex AGENTS.md at ${agentsFilePath}: ${String(cause)}`,
      ),
  });
  yield* Effect.tryPromise({
    try: () => fs.writeFile(agentsFilePath, content, "utf8"),
    catch: (cause) =>
      caaraCodexRoleInstallerError(
        `Failed to write Codex AGENTS.md at ${agentsFilePath}: ${String(cause)}`,
      ),
  });
  return agentsFilePath;
});

/** Persists one computed guidance document update to disk. */
const applyGuidanceUpdate = Effect.fnUntraced(function* ({
  agentsFilePath,
  update,
}: {
  readonly agentsFilePath: string;
  readonly update: CodexAgentsGuidanceUpdate;
}) {
  return yield* Match.valueTags(update, {
    Corrupt: ({ reason }) =>
      Effect.fail(
        caaraCodexRoleInstallerError(
          `Refusing to update Codex AGENTS.md at ${agentsFilePath}: ${reason}. Repair or remove the caara:agents markers first.`,
        ),
      ),
    Delete: () =>
      Effect.tryPromise({
        try: () => fs.rm(agentsFilePath, { force: true }),
        catch: (cause) =>
          caaraCodexRoleInstallerError(
            `Failed to remove Codex AGENTS.md at ${agentsFilePath}: ${String(cause)}`,
          ),
      }).pipe(Effect.map(() => agentsFilePath)),
    Unchanged: () => Effect.sync(() => undefined),
    Write: ({ content }) => writeGuidanceContent({ agentsFilePath, content }),
  });
});

/**
 * Returns the corruption reason when the guidance file carries a broken marker pair,
 * or undefined when the file is absent, unmanaged, or holds a well-formed managed block.
 */
export const preflightCodexAgentsGuidanceFile = Effect.fnUntraced(function* ({
  agentsFilePath,
}: {
  readonly agentsFilePath: string;
}) {
  const source = yield* readGuidanceFile({ agentsFilePath });
  return Match.value(locateMarkerSpan({ source: source ?? "" })).pipe(
    Match.tag("Corrupt", ({ reason }) => reason),
    Match.orElse(() => undefined),
  );
});

/** Writes or refreshes the managed guidance block inside the global Codex AGENTS.md. */
export const writeCodexAgentsGuidanceFile = Effect.fnUntraced(function* ({
  agentsFilePath,
  panelSkillInstalled,
}: {
  readonly agentsFilePath: string;
  readonly panelSkillInstalled: boolean;
}) {
  const source = yield* readGuidanceFile({ agentsFilePath });
  const block = renderCodexAgentsGuidanceBlock({ panelSkillInstalled });
  return yield* applyGuidanceUpdate({
    agentsFilePath,
    update: upsertCodexAgentsGuidance({ block, source }),
  });
});

/** Removes the managed guidance block from the global Codex AGENTS.md when present. */
export const removeCodexAgentsGuidanceFile = Effect.fnUntraced(function* ({
  agentsFilePath,
}: {
  readonly agentsFilePath: string;
}) {
  const source = yield* readGuidanceFile({ agentsFilePath });
  const updatedPaths = yield* Effect.forEach(
    [source].filter((existing) => existing !== undefined),
    (existing) =>
      applyGuidanceUpdate({
        agentsFilePath,
        update: removeCodexAgentsGuidance({ source: existing }),
      }),
    { concurrency: 1 },
  );
  return updatedPaths.at(0);
});
