/** One generated Codex role file definition. */
export interface CaaraCodexRoleDefinition {
  readonly description: string;
  readonly developerInstructions: string;
  readonly model: string;
  readonly name: string;
}

/** One installable external driver catalog for generated Codex roles. */
export interface CaaraCodexRoleDriverCatalog {
  readonly driverName: string;
  readonly executableName: string;
  readonly roles: readonly CaaraCodexRoleDefinition[];
}

/** Claude role variants generated by the safe default role installer. */
export const claudeCodexRoleDefinitions: readonly CaaraCodexRoleDefinition[] = [
  {
    name: "caara-claude-haiku",
    description: "Delegates to the local Caara Responses provider backed by Claude Haiku.",
    developerInstructions:
      "Use the local Caara Responses provider with Claude Haiku. Relay the provider response as-is.",
    model: "claude/haiku",
  },
  {
    name: "caara-claude-sonnet",
    description: "Delegates to the local Caara Responses provider backed by Claude Sonnet.",
    developerInstructions:
      "Use the local Caara Responses provider with Claude Sonnet. Relay the provider response as-is.",
    model: "claude/sonnet",
  },
  {
    name: "caara-claude-opus",
    description: "Delegates to the local Caara Responses provider backed by Claude Opus.",
    developerInstructions:
      "Use the local Caara Responses provider with Claude Opus. Relay the provider response as-is.",
    model: "claude/opus",
  },
  {
    name: "caara-claude-fable",
    description: "Delegates to the local Caara Responses provider backed by Claude Fable.",
    developerInstructions:
      "Use the local Caara Responses provider with Claude Fable. Relay the provider response as-is.",
    model: "claude/fable",
  },
];

/** Antigravity role variants generated by the safe default role installer. */
export const antigravityCodexRoleDefinitions: readonly CaaraCodexRoleDefinition[] = [
  {
    name: "caara-agy-gemini-3-5-flash",
    description: "Delegates to the local Caara Responses provider backed by Gemini 3.5 Flash.",
    developerInstructions:
      "Use the local Caara Responses provider with Antigravity Gemini 3.5 Flash. Relay the provider response as-is.",
    model: "agy/gemini-3.5-flash",
  },
  {
    name: "caara-agy-gemini-3-1-pro",
    description: "Delegates to the local Caara Responses provider backed by Gemini 3.1 Pro.",
    developerInstructions:
      "Use the local Caara Responses provider with Antigravity Gemini 3.1 Pro. Relay the provider response as-is.",
    model: "agy/gemini-3.1-pro",
  },
  {
    name: "caara-agy-claude-sonnet-4-6",
    description: "Delegates to the local Caara Responses provider backed by Claude Sonnet 4.6.",
    developerInstructions:
      "Use the local Caara Responses provider with Antigravity Claude Sonnet 4.6. Relay the provider response as-is.",
    model: "agy/claude-sonnet-4.6",
  },
  {
    name: "caara-agy-claude-opus-4-6",
    description: "Delegates to the local Caara Responses provider backed by Claude Opus 4.6.",
    developerInstructions:
      "Use the local Caara Responses provider with Antigravity Claude Opus 4.6. Relay the provider response as-is.",
    model: "agy/claude-opus-4.6",
  },
  {
    name: "caara-agy-gpt-oss-120b",
    description: "Delegates to the local Caara Responses provider backed by GPT-OSS 120B.",
    developerInstructions:
      "Use the local Caara Responses provider with Antigravity GPT-OSS 120B. Relay the provider response as-is.",
    model: "agy/gpt-oss-120b",
  },
];

/** Installed role catalogs owned by Caara. */
export const safeCodexRoleDriverCatalogs: readonly CaaraCodexRoleDriverCatalog[] = [
  {
    driverName: "Claude",
    executableName: "claude",
    roles: claudeCodexRoleDefinitions,
  },
  {
    driverName: "Antigravity",
    executableName: "agy",
    roles: antigravityCodexRoleDefinitions,
  },
];

/** All role definitions Caara may manage by generated filename. */
export const allSafeCodexRoleDefinitions: readonly CaaraCodexRoleDefinition[] =
  safeCodexRoleDriverCatalogs.flatMap((catalog) => catalog.roles);
