import { randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

import { assert, describe, it } from "@effect/vitest";
import { TOML } from "bun";
import { Effect, Schema } from "effect";

import { runCaaraInstallCodexRoles } from "./codexRoleInstaller.ts";

/** Builds one isolated yolo role installer test root under temp.local. */
const testRoot = (): string =>
  path.join(process.cwd(), "temp.local", "2026-07-03", `codex-roles-yolo-${randomUUID()}`);

/** Writes one test fixture file and creates its parent directory. */
const writeFile = Effect.fnUntraced(function* ({
  filePath,
  content,
}: {
  readonly filePath: string;
  readonly content: string;
}) {
  yield* Effect.tryPromise(() => fs.mkdir(path.dirname(filePath), { recursive: true }));
  yield* Effect.tryPromise(() => fs.writeFile(filePath, content, "utf8"));
});

/** Writes one executable fixture on the test PATH. */
const writeExecutable = Effect.fnUntraced(function* ({ filePath }: { readonly filePath: string }) {
  yield* writeFile({ filePath, content: "#!/bin/sh\n" });
  yield* Effect.tryPromise(() => fs.chmod(filePath, 0o755));
});

/** Reads one UTF-8 text fixture. */
const readFile = Effect.fnUntraced(function* ({ filePath }: { readonly filePath: string }) {
  return yield* Effect.tryPromise(() => fs.readFile(filePath, "utf8"));
});

/** Minimal generated-role provider config with arbitrary query params. */
const YoloRoleProviderConfig = Schema.Struct({
  query_params: Schema.Record(Schema.String, Schema.String),
});

/** Minimal generated-role config shape needed by yolo role tests. */
const YoloRoleConfig = Schema.Struct({
  model_providers: Schema.Struct({
    caara: YoloRoleProviderConfig,
  }),
});

/** Tagged failure for yolo role TOML parse errors. */
class YoloRoleConfigTestError extends Schema.TaggedErrorClass<YoloRoleConfigTestError>()(
  "YoloRoleConfigTestError",
  {
    message: Schema.String,
  },
) {}

/** Converts unknown role config parse failures into a tagged test error. */
const yoloRoleConfigTestError = (cause: unknown): YoloRoleConfigTestError =>
  new YoloRoleConfigTestError({ message: String(cause) });

/** Parses one generated role file for yolo query param assertions. */
const parseYoloRole = Effect.fnUntraced(function* ({ filePath }: { readonly filePath: string }) {
  const source = yield* readFile({ filePath });
  const parsed = yield* Effect.try({
    try: () => TOML.parse(source),
    catch: yoloRoleConfigTestError,
  });
  const config = yield* Schema.decodeUnknownEffect(YoloRoleConfig)(parsed);
  return { config, source };
});

/** Builds a role installer environment with only the fields needed by tests. */
const roleEnv = ({ home, pathValue }: { readonly home: string; readonly pathValue: string }) => ({
  HOME: home,
  PATH: pathValue,
});

/** Marked generated role fixture with arbitrary query params. */
const markedRoleToml = ({
  model,
  name,
  queryParams,
}: {
  readonly model: string;
  readonly name: string;
  readonly queryParams: string;
}): string =>
  [
    "# Generated by Caara. Do not edit directly.",
    "# caara-generated-role = true",
    `name = "${name}"`,
    'description = "Old generated description"',
    'developer_instructions = "Old instructions"',
    'model_provider = "caara"',
    `model = "${model}"`,
    "model_supports_reasoning_summaries = true",
    "",
    "[model_providers.caara]",
    'name = "Caara Responses"',
    'base_url = "http://127.0.0.1:8787/v1"',
    'wire_api = "responses"',
    "requires_openai_auth = false",
    "request_max_retries = 0",
    "stream_max_retries = 0",
    `query_params = { ${queryParams} }`,
    "",
  ].join("\n");

describe("Caara yolo Codex role installer", () => {
  it.effect(
    "fails yolo role installation when the selected service config lacks the dangerous gate",
    () =>
      Effect.gen(function* () {
        const root = testRoot();
        const binDir = path.join(root, "bin");
        const targetDirectory = path.join(root, "agents");
        const configPath = path.join(root, "config", "caara.yaml");
        yield* writeExecutable({ filePath: path.join(binDir, "claude") });
        yield* writeFile({
          filePath: configPath,
          content: "allowDangerousSkipPermissions: false\n",
        });

        const result = yield* runCaaraInstallCodexRoles({
          args: ["--yolo", "--config", configPath, targetDirectory],
          env: roleEnv({ home: path.join(root, "home"), pathValue: binDir }),
        });

        assert.strictEqual(result.exitCode, 1);
        assert.match(result.message, /requires allowDangerousSkipPermissions: true/u);
      }),
  );

  it.effect("sets yolo dangerous query params without forcing Antigravity sandbox off", () =>
    Effect.gen(function* () {
      const root = testRoot();
      const binDir = path.join(root, "bin");
      const targetDirectory = path.join(root, "agents");
      const configPath = path.join(root, "config", "caara.yaml");
      yield* writeExecutable({ filePath: path.join(binDir, "claude") });
      yield* writeExecutable({ filePath: path.join(binDir, "agy") });
      yield* writeFile({ filePath: configPath, content: "allowDangerousSkipPermissions: true\n" });

      const result = yield* runCaaraInstallCodexRoles({
        args: ["--yolo", "--config", configPath, targetDirectory],
        env: roleEnv({ home: path.join(root, "home"), pathValue: binDir }),
      });
      const claude = yield* parseYoloRole({
        filePath: path.join(targetDirectory, "caara-claude-haiku.toml"),
      });
      const agy = yield* parseYoloRole({
        filePath: path.join(targetDirectory, "caara-agy-gemini-3-5-flash.toml"),
      });

      assert.strictEqual(result.exitCode, 0);
      assert.strictEqual(
        claude.config.model_providers.caara.query_params.permission_mode,
        "bypassPermissions",
      );
      assert.strictEqual(
        agy.config.model_providers.caara.query_params.dangerously_skip_permissions,
        "true",
      );
      assert.ok(!("sandbox" in agy.config.model_providers.caara.query_params));
      assert.ok(!agy.source.includes("sandbox"));
    }),
  );

  it.effect("sets or removes yolo danger keys while preserving unrelated query params", () =>
    Effect.gen(function* () {
      const root = testRoot();
      const binDir = path.join(root, "bin");
      const targetDirectory = path.join(root, "agents");
      const configPath = path.join(root, "config", "caara.yaml");
      yield* writeExecutable({ filePath: path.join(binDir, "claude") });
      yield* writeExecutable({ filePath: path.join(binDir, "agy") });
      yield* writeFile({ filePath: configPath, content: "allowDangerousSkipPermissions: true\n" });
      yield* writeFile({
        filePath: path.join(targetDirectory, "caara-claude-haiku.toml"),
        content: markedRoleToml({
          model: "claude/haiku",
          name: "caara-claude-haiku",
          queryParams: 'custom_option = "keep", permission_mode = "auto"',
        }),
      });
      yield* writeFile({
        filePath: path.join(targetDirectory, "caara-agy-gemini-3-5-flash.toml"),
        content: markedRoleToml({
          model: "agy/gemini-3.5-flash",
          name: "caara-agy-gemini-3-5-flash",
          queryParams:
            'custom_option = "keep", dangerously_skip_permissions = "false", sandbox = "true"',
        }),
      });

      yield* runCaaraInstallCodexRoles({
        args: ["--yolo", "--config", configPath, targetDirectory],
        env: roleEnv({ home: path.join(root, "home"), pathValue: binDir }),
      });
      const yoloClaude = yield* parseYoloRole({
        filePath: path.join(targetDirectory, "caara-claude-haiku.toml"),
      });
      const yoloAgy = yield* parseYoloRole({
        filePath: path.join(targetDirectory, "caara-agy-gemini-3-5-flash.toml"),
      });

      yield* runCaaraInstallCodexRoles({
        args: [targetDirectory],
        env: roleEnv({ home: path.join(root, "home"), pathValue: binDir }),
      });
      const safeClaude = yield* parseYoloRole({
        filePath: path.join(targetDirectory, "caara-claude-haiku.toml"),
      });
      const safeAgy = yield* parseYoloRole({
        filePath: path.join(targetDirectory, "caara-agy-gemini-3-5-flash.toml"),
      });

      assert.deepStrictEqual(yoloClaude.config.model_providers.caara.query_params, {
        custom_option: "keep",
        permission_mode: "bypassPermissions",
      });
      assert.deepStrictEqual(yoloAgy.config.model_providers.caara.query_params, {
        custom_option: "keep",
        dangerously_skip_permissions: "true",
        sandbox: "true",
      });
      assert.deepStrictEqual(safeClaude.config.model_providers.caara.query_params, {
        custom_option: "keep",
      });
      assert.deepStrictEqual(safeAgy.config.model_providers.caara.query_params, {
        custom_option: "keep",
        sandbox: "true",
      });
    }),
  );
});
