import { constants as fsConstants } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";

import { Console, Effect, Match, Option, Schema } from "effect";

import { pathEntriesFromValue } from "./caaraExecutionPath.ts";

/** Environment fields consumed by standalone Codex role installation. */
export interface CaaraCodexRoleInstallerEnvironment {
  readonly CODEX_HOME?: string | undefined;
  readonly HOME?: string | undefined;
  readonly PATH?: string | undefined;
}

/** One skipped installed-role driver report. */
export interface CaaraCodexRoleSkippedDriver {
  readonly driverName: string;
  readonly executableName: string;
  readonly reason: string;
}

/** In-process result returned by Codex role installation. */
export interface CaaraCodexRoleInstallResult {
  readonly exitCode: 0 | 1;
  readonly message: string;
  readonly skippedDrivers: readonly CaaraCodexRoleSkippedDriver[];
  readonly targetDirectory: string;
  readonly writtenFiles: readonly string[];
}

/** Options accepted by in-process Codex role installation. */
export interface RunCaaraInstallCodexRolesOptions {
  readonly args: readonly string[];
  readonly env?: CaaraCodexRoleInstallerEnvironment;
}

/** Options accepted by the live Codex role installation CLI wrapper. */
export interface RunCaaraInstallCodexRolesCliOptions {
  readonly args: readonly string[];
}

/** Failure while installing generated Codex roles. */
export class CaaraCodexRoleInstallerError extends Schema.TaggedErrorClass<CaaraCodexRoleInstallerError>()(
  "CaaraCodexRoleInstallerError",
  {
    message: Schema.String,
  },
) {}

/** One generated Codex role file definition. */
export interface CaaraCodexRoleDefinition {
  readonly description: string;
  readonly developerInstructions: string;
  readonly model: string;
  readonly name: string;
}

/** One installable external driver catalog for generated Codex roles. */
export interface CaaraCodexRoleDriverCatalog {
  readonly driverName: string;
  readonly executableName: string;
  readonly roles: readonly CaaraCodexRoleDefinition[];
}

/** Successful driver availability detection result. */
interface AvailableRoleDriver {
  readonly _tag: "Available";
  readonly catalog: CaaraCodexRoleDriverCatalog;
  readonly executablePath: string;
}

/** Skipped driver availability detection result. */
interface SkippedRoleDriver {
  readonly _tag: "Skipped";
  readonly driverName: string;
  readonly executableName: string;
  readonly reason: string;
}

/** Driver availability detection result. */
type DetectedRoleDriver = AvailableRoleDriver | SkippedRoleDriver;

/** Returns the Caara marker included in every generated installed Codex role file. */
const caaraGeneratedCodexRoleMarker = (): string =>
  "# Generated by Caara. Do not edit directly.\n# caara-generated-role = true";

/** Claude role variants generated by the safe default role installer. */
export const claudeCodexRoleDefinitions: readonly CaaraCodexRoleDefinition[] = [
  {
    name: "caara-claude-haiku",
    description: "Delegates to the local Caara Responses provider backed by Claude Haiku.",
    developerInstructions:
      "Use the local Caara Responses provider with Claude Haiku. Relay the provider response as-is.",
    model: "claude/haiku",
  },
  {
    name: "caara-claude-sonnet",
    description: "Delegates to the local Caara Responses provider backed by Claude Sonnet.",
    developerInstructions:
      "Use the local Caara Responses provider with Claude Sonnet. Relay the provider response as-is.",
    model: "claude/sonnet",
  },
  {
    name: "caara-claude-opus",
    description: "Delegates to the local Caara Responses provider backed by Claude Opus.",
    developerInstructions:
      "Use the local Caara Responses provider with Claude Opus. Relay the provider response as-is.",
    model: "claude/opus",
  },
  {
    name: "caara-claude-fable",
    description: "Delegates to the local Caara Responses provider backed by Claude Fable.",
    developerInstructions:
      "Use the local Caara Responses provider with Claude Fable. Relay the provider response as-is.",
    model: "claude/fable",
  },
];

/** Antigravity role variants generated by the safe default role installer. */
export const antigravityCodexRoleDefinitions: readonly CaaraCodexRoleDefinition[] = [
  {
    name: "caara-agy-gemini-3-5-flash",
    description: "Delegates to the local Caara Responses provider backed by Gemini 3.5 Flash.",
    developerInstructions:
      "Use the local Caara Responses provider with Antigravity Gemini 3.5 Flash. Relay the provider response as-is.",
    model: "agy/gemini-3.5-flash",
  },
  {
    name: "caara-agy-gemini-3-1-pro",
    description: "Delegates to the local Caara Responses provider backed by Gemini 3.1 Pro.",
    developerInstructions:
      "Use the local Caara Responses provider with Antigravity Gemini 3.1 Pro. Relay the provider response as-is.",
    model: "agy/gemini-3.1-pro",
  },
  {
    name: "caara-agy-claude-sonnet-4-6",
    description: "Delegates to the local Caara Responses provider backed by Claude Sonnet 4.6.",
    developerInstructions:
      "Use the local Caara Responses provider with Antigravity Claude Sonnet 4.6. Relay the provider response as-is.",
    model: "agy/claude-sonnet-4.6",
  },
  {
    name: "caara-agy-claude-opus-4-6",
    description: "Delegates to the local Caara Responses provider backed by Claude Opus 4.6.",
    developerInstructions:
      "Use the local Caara Responses provider with Antigravity Claude Opus 4.6. Relay the provider response as-is.",
    model: "agy/claude-opus-4.6",
  },
  {
    name: "caara-agy-gpt-oss-120b",
    description: "Delegates to the local Caara Responses provider backed by GPT-OSS 120B.",
    developerInstructions:
      "Use the local Caara Responses provider with Antigravity GPT-OSS 120B. Relay the provider response as-is.",
    model: "agy/gpt-oss-120b",
  },
];

/** Installed role catalogs available in this implementation slice. */
export const safeCodexRoleDriverCatalogs: readonly CaaraCodexRoleDriverCatalog[] = [
  {
    driverName: "Claude",
    executableName: "claude",
    roles: claudeCodexRoleDefinitions,
  },
  {
    driverName: "Antigravity",
    executableName: "agy",
    roles: antigravityCodexRoleDefinitions,
  },
];

/** Builds one typed Codex role installer failure. */
const caaraCodexRoleInstallerError = (message: string): CaaraCodexRoleInstallerError =>
  new CaaraCodexRoleInstallerError({ message });

/** Escapes a string as a TOML basic string. */
const tomlString = (value: string): string =>
  `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"').replaceAll("\n", "\\n").replaceAll("\r", "\\r").replaceAll("\t", "\\t")}"`;

/** Reads role installer environment fields from the host process. */
const processCodexRoleInstallerEnvironment = (): CaaraCodexRoleInstallerEnvironment => ({
  CODEX_HOME: process.env.CODEX_HOME,
  HOME: process.env.HOME,
  PATH: process.env.PATH,
});

/** Returns true when an environment path value can be used. */
const hasNonEmptyPath = (value: string): boolean => value.length > 0;

/** Resolves the default Codex agents directory from CODEX_HOME or HOME. */
export const defaultCodexAgentsDirectory = ({
  env,
}: {
  readonly env: CaaraCodexRoleInstallerEnvironment;
}): string | undefined =>
  Option.match(Option.fromUndefinedOr(env.CODEX_HOME).pipe(Option.filter(hasNonEmptyPath)), {
    onNone: () =>
      Option.match(Option.fromUndefinedOr(env.HOME).pipe(Option.filter(hasNonEmptyPath)), {
        onNone: () => undefined,
        onSome: (home) => path.join(home, ".codex", "agents"),
      }),
    onSome: (codexHome) => path.join(codexHome, "agents"),
  });

/** Resolves the target directory selected by install-codex-roles args. */
const targetDirectoryFromArgs = ({
  args,
  env,
}: {
  readonly args: readonly string[];
  readonly env: CaaraCodexRoleInstallerEnvironment;
}): string | undefined =>
  Match.value(args.length).pipe(
    Match.when(0, () => defaultCodexAgentsDirectory({ env })),
    Match.when(1, () => args.at(0)),
    Match.orElse(() => undefined),
  );

/** Checks whether one candidate path is executable. */
const isExecutableFile = Effect.fnUntraced(function* ({ filePath }: { readonly filePath: string }) {
  return yield* Effect.tryPromise({
    try: () =>
      fs
        .access(filePath, fsConstants.X_OK)
        .then(() => true)
        .catch(() => false),
    catch: () => false,
  });
});

/** Finds the first executable with the given name in the invoking shell PATH. */
const findShellExecutable = Effect.fnUntraced(function* ({
  executableName,
  env,
}: {
  readonly executableName: string;
  readonly env: CaaraCodexRoleInstallerEnvironment;
}) {
  const candidates = pathEntriesFromValue(env.PATH).map((entry) =>
    path.join(entry, executableName),
  );
  const availability = yield* Effect.forEach(
    candidates,
    (candidate) =>
      isExecutableFile({ filePath: candidate }).pipe(
        Effect.map((executable) => [candidate].filter(() => executable).at(0)),
      ),
    { concurrency: 1 },
  );
  return availability.find((candidate) => candidate !== undefined);
});

/** Detects whether one role driver catalog is available from the invoking shell PATH. */
const detectRoleDriver = Effect.fnUntraced(function* ({
  catalog,
  env,
}: {
  readonly catalog: CaaraCodexRoleDriverCatalog;
  readonly env: CaaraCodexRoleInstallerEnvironment;
}) {
  const executablePath = yield* findShellExecutable({
    env,
    executableName: catalog.executableName,
  });
  return Option.match(Option.fromUndefinedOr(executablePath), {
    onNone: () =>
      ({
        _tag: "Skipped",
        driverName: catalog.driverName,
        executableName: catalog.executableName,
        reason: "command not found on PATH",
      }) satisfies DetectedRoleDriver,
    onSome: (foundPath) =>
      ({
        _tag: "Available",
        catalog,
        executablePath: foundPath,
      }) satisfies DetectedRoleDriver,
  });
});

/** Detects available role catalogs and skipped drivers from the invoking shell PATH. */
const detectRoleDrivers = Effect.fnUntraced(function* ({
  env,
}: {
  readonly env: CaaraCodexRoleInstallerEnvironment;
}) {
  return yield* Effect.forEach(
    safeCodexRoleDriverCatalogs,
    (catalog) => detectRoleDriver({ catalog, env }),
    { concurrency: 1 },
  );
});

/** Renders one generated Codex role as parseable TOML. */
export const renderCodexRoleToml = (role: CaaraCodexRoleDefinition): string =>
  [
    caaraGeneratedCodexRoleMarker(),
    `name = ${tomlString(role.name)}`,
    `description = ${tomlString(role.description)}`,
    `developer_instructions = ${tomlString(role.developerInstructions)}`,
    'model_provider = "caara"',
    `model = ${tomlString(role.model)}`,
    "model_supports_reasoning_summaries = true",
    "",
    "[model_providers.caara]",
    'name = "Caara Responses"',
    'base_url = "http://127.0.0.1:8787/v1"',
    'wire_api = "responses"',
    "requires_openai_auth = false",
    "request_max_retries = 0",
    "stream_max_retries = 0",
    "query_params = {}",
    "",
  ].join("\n");

/** Writes one generated role file into the target directory. */
const writeRoleFile = Effect.fnUntraced(function* ({
  role,
  targetDirectory,
}: {
  readonly role: CaaraCodexRoleDefinition;
  readonly targetDirectory: string;
}) {
  const filePath = path.join(targetDirectory, `${role.name}.toml`);
  yield* Effect.tryPromise({
    try: () => fs.writeFile(filePath, renderCodexRoleToml(role), "utf8"),
    catch: (cause) =>
      caaraCodexRoleInstallerError(
        `Failed to write generated Codex role ${filePath}: ${String(cause)}`,
      ),
  });
  return filePath;
});

/** Flattens available role catalogs to generated role definitions. */
const rolesFromAvailableDrivers = (detected: readonly DetectedRoleDriver[]) =>
  detected
    .filter((driver): driver is AvailableRoleDriver => driver._tag === "Available")
    .flatMap((driver) => driver.catalog.roles);

/** Builds skipped-driver reports from detection results. */
const skippedDriversFromDetected = (
  detected: readonly DetectedRoleDriver[],
): readonly CaaraCodexRoleSkippedDriver[] =>
  detected
    .filter((driver): driver is SkippedRoleDriver => driver._tag === "Skipped")
    .map(({ driverName, executableName, reason }) => ({
      driverName,
      executableName,
      reason,
    }));

/** Formats the role installer result message. */
const formatInstallResultMessage = ({
  skippedDrivers,
  targetDirectory,
  writtenFiles,
}: {
  readonly skippedDrivers: readonly CaaraCodexRoleSkippedDriver[];
  readonly targetDirectory: string;
  readonly writtenFiles: readonly string[];
}): string =>
  [
    `installed ${writtenFiles.length} Codex roles to ${targetDirectory}`,
    ...skippedDrivers.map(
      (driver) => `skipped ${driver.driverName}: ${driver.executableName} ${driver.reason}`,
    ),
  ].join("\n");

/** Builds an invalid install-codex-roles result without writing files. */
const invalidInstallResult = ({
  message,
}: {
  readonly message: string;
}): CaaraCodexRoleInstallResult => ({
  exitCode: 1,
  message,
  skippedDrivers: [],
  targetDirectory: "",
  writtenFiles: [],
});

/** Runs `caara install-codex-roles` without terminating the host process. */
export const runCaaraInstallCodexRoles = Effect.fnUntraced(function* ({
  args,
  env = processCodexRoleInstallerEnvironment(),
}: RunCaaraInstallCodexRolesOptions) {
  const targetDirectory = targetDirectoryFromArgs({ args, env });
  return yield* Option.match(Option.fromUndefinedOr(targetDirectory), {
    onNone: () =>
      Effect.succeed(
        invalidInstallResult({
          message:
            "caara install-codex-roles requires zero arguments or one target directory, and HOME or CODEX_HOME must be set.",
        }),
      ),
    onSome: (resolvedTargetDirectory) =>
      Effect.gen(function* () {
        yield* Effect.tryPromise({
          try: () => fs.mkdir(resolvedTargetDirectory, { recursive: true }),
          catch: (cause) =>
            caaraCodexRoleInstallerError(
              `Failed to create Codex roles directory ${resolvedTargetDirectory}: ${String(cause)}`,
            ),
        });
        const detected = yield* detectRoleDrivers({ env });
        const roles = rolesFromAvailableDrivers(detected);
        const writtenFiles = yield* Effect.forEach(
          roles,
          (role) => writeRoleFile({ role, targetDirectory: resolvedTargetDirectory }),
          { concurrency: 1 },
        );
        const skippedDrivers = skippedDriversFromDetected(detected);
        return {
          exitCode: 0,
          message: formatInstallResultMessage({
            skippedDrivers,
            targetDirectory: resolvedTargetDirectory,
            writtenFiles,
          }),
          skippedDrivers,
          targetDirectory: resolvedTargetDirectory,
          writtenFiles,
        } satisfies CaaraCodexRoleInstallResult;
      }),
  });
});

/** Runs live `install-codex-roles` and fails for nonzero status. */
export const runCaaraInstallCodexRolesCli = Effect.fnUntraced(function* ({
  args,
}: RunCaaraInstallCodexRolesCliOptions) {
  const result = yield* runCaaraInstallCodexRoles({ args });
  yield* Console.log(result.message);
  return yield* Option.match(
    Option.fromUndefinedOr([result].filter(({ exitCode }) => exitCode !== 0).at(0)),
    {
      onNone: () => Effect.void,
      onSome: (failure) => Effect.fail(caaraCodexRoleInstallerError(failure.message)),
    },
  );
});
