import { TOML } from "bun";
import { Effect, Match, Schema } from "effect";

import type { CaaraCodexRoleDefinition } from "./codexRoleCatalog.ts";

/** Query parameters preserved and rendered inside the Caara model provider block. */
export type CodexRoleQueryParams = Readonly<Record<string, string>>;

/** Options required to render one generated Codex role file. */
export interface RenderCodexRoleTomlOptions {
  readonly baseUrl: string;
  readonly queryParams: CodexRoleQueryParams;
  readonly role: CaaraCodexRoleDefinition;
}

/** Failure while parsing an existing generated Codex role. */
export class CodexRoleTomlError extends Schema.TaggedErrorClass<CodexRoleTomlError>()(
  "CodexRoleTomlError",
  {
    message: Schema.String,
  },
) {}

/** Existing generated-role provider config shape used for query-param preservation. */
const ExistingRoleProviderConfig = Schema.Struct({
  query_params: Schema.Record(Schema.String, Schema.String),
});

/** Existing generated-role TOML shape used for query-param preservation. */
const ExistingRoleConfig = Schema.Struct({
  model_providers: Schema.Struct({
    caara: ExistingRoleProviderConfig,
  }),
});

/** Builds one TOML parsing failure. */
const codexRoleTomlError = (cause: unknown): CodexRoleTomlError =>
  new CodexRoleTomlError({ message: String(cause) });

/** Returns the Caara marker included in every generated installed Codex role file. */
export const caaraGeneratedCodexRoleMarker = (): string =>
  "# Generated by Caara. Do not edit directly.\n# caara-generated-role = true";

/** Returns whether source text is marked as a Caara-generated Codex role. */
export const isCaaraGeneratedCodexRole = (source: string): boolean =>
  source.includes("# caara-generated-role = true");

/** Escapes a string as a TOML basic string. */
const tomlString = (value: string): string =>
  `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"').replaceAll("\n", "\\n").replaceAll("\r", "\\r").replaceAll("\t", "\\t")}"`;

/** Renders query params as a TOML inline table. */
const renderQueryParams = (queryParams: CodexRoleQueryParams): string => {
  const entries = Object.entries(queryParams).toSorted(([left], [right]) =>
    left.localeCompare(right),
  );
  return Match.value(entries.length).pipe(
    Match.when(0, () => "{}"),
    Match.orElse(
      () =>
        `{ ${entries.map(([key, value]) => `${tomlString(key)} = ${tomlString(value)}`).join(", ")} }`,
    ),
  );
};

/** Renders one generated Codex role as parseable TOML. */
export const renderCodexRoleToml = ({
  baseUrl,
  queryParams,
  role,
}: RenderCodexRoleTomlOptions): string =>
  [
    caaraGeneratedCodexRoleMarker(),
    `name = ${tomlString(role.name)}`,
    `description = ${tomlString(role.description)}`,
    `developer_instructions = ${tomlString(role.developerInstructions)}`,
    'model_provider = "caara"',
    `model = ${tomlString(role.model)}`,
    "model_supports_reasoning_summaries = true",
    "",
    "[model_providers.caara]",
    'name = "Caara Responses"',
    `base_url = ${tomlString(baseUrl)}`,
    'wire_api = "responses"',
    "requires_openai_auth = false",
    "request_max_retries = 0",
    "stream_max_retries = 0",
    `query_params = ${renderQueryParams(queryParams)}`,
    "",
  ].join("\n");

/** Parses preserved query params from an existing Caara-marked role. */
export const parseCodexRoleQueryParams = Effect.fnUntraced(function* ({
  source,
}: {
  readonly source: string;
}) {
  const parsed = yield* Effect.try({
    try: () => TOML.parse(source),
    catch: codexRoleTomlError,
  });
  const config = yield* Schema.decodeUnknownEffect(ExistingRoleConfig)(parsed).pipe(
    Effect.mapError(codexRoleTomlError),
  );
  return config.model_providers.caara.query_params;
});
