import { randomUUID } from "node:crypto";
import * as fs from "node:fs/promises";
import path from "node:path";

import { assert, describe, it } from "@effect/vitest";
import { TOML } from "bun";
import { Effect, Schema } from "effect";

import { runCaaraInstallCodexRoles, runCaaraUninstallCodexRoles } from "./codexRoleInstaller.ts";

/** Builds one isolated managed-role test root under temp.local. */
const testRoot = (): string =>
  path.join(process.cwd(), "temp.local", "2026-07-03", `codex-roles-managed-${randomUUID()}`);

/** Writes one test fixture file and creates its parent directory. */
const writeFile = Effect.fnUntraced(function* ({
  filePath,
  content,
}: {
  readonly filePath: string;
  readonly content: string;
}) {
  yield* Effect.tryPromise(() => fs.mkdir(path.dirname(filePath), { recursive: true }));
  yield* Effect.tryPromise(() => fs.writeFile(filePath, content, "utf8"));
});

/** Writes one executable fixture on the test PATH. */
const writeExecutable = Effect.fnUntraced(function* ({ filePath }: { readonly filePath: string }) {
  yield* writeFile({ filePath, content: "#!/bin/sh\n" });
  yield* Effect.tryPromise(() => fs.chmod(filePath, 0o755));
});

/** Reads one UTF-8 text fixture. */
const readFile = Effect.fnUntraced(function* ({ filePath }: { readonly filePath: string }) {
  return yield* Effect.tryPromise(() => fs.readFile(filePath, "utf8"));
});

/** Returns whether one path exists. */
const pathExists = Effect.fnUntraced(function* ({ filePath }: { readonly filePath: string }) {
  return yield* Effect.tryPromise(() => Bun.file(filePath).exists());
});

/** Lists filenames in one directory in deterministic order. */
const listFilenames = Effect.fnUntraced(function* ({ dirPath }: { readonly dirPath: string }) {
  const entries = yield* Effect.tryPromise(() => fs.readdir(dirPath));
  return entries.toSorted();
});

/** Minimal generated-role provider config with arbitrary query params. */
const ManagedRoleProviderConfig = Schema.Struct({
  query_params: Schema.Record(Schema.String, Schema.String),
});

/** Minimal generated-role config shape needed by managed-role tests. */
const ManagedRoleConfig = Schema.Struct({
  description: Schema.String,
  model_providers: Schema.Struct({
    caara: ManagedRoleProviderConfig,
  }),
});

/** Tagged failure for managed-role TOML parse errors. */
class ManagedRoleConfigTestError extends Schema.TaggedErrorClass<ManagedRoleConfigTestError>()(
  "ManagedRoleConfigTestError",
  {
    message: Schema.String,
  },
) {}

/** Converts unknown role config parse failures into a tagged test error. */
const managedRoleConfigTestError = (cause: unknown): ManagedRoleConfigTestError =>
  new ManagedRoleConfigTestError({ message: String(cause) });

/** Parses one generated role file for managed-role assertions. */
const parseManagedRole = Effect.fnUntraced(function* ({ filePath }: { readonly filePath: string }) {
  const source = yield* readFile({ filePath });
  const parsed = yield* Effect.try({
    try: () => TOML.parse(source),
    catch: managedRoleConfigTestError,
  });
  const config = yield* Schema.decodeUnknownEffect(ManagedRoleConfig)(parsed);
  return { config, source };
});

/** Builds a role installer environment with only the fields needed by tests. */
const roleEnv = ({ home, pathValue }: { readonly home: string; readonly pathValue: string }) => ({
  HOME: home,
  PATH: pathValue,
});

/** Marked stale role fixture with customizable query params. */
const markedRoleToml = (): string =>
  [
    "# Generated by Caara. Do not edit directly.",
    "# caara-generated-role = true",
    'name = "caara-claude-haiku"',
    'description = "Old generated description"',
    'developer_instructions = "Old instructions"',
    'model_provider = "caara"',
    'model = "claude/haiku"',
    "model_supports_reasoning_summaries = true",
    "",
    "[model_providers.caara]",
    'name = "Caara Responses"',
    'base_url = "http://127.0.0.1:8787/v1"',
    'wire_api = "responses"',
    "requires_openai_auth = false",
    "request_max_retries = 0",
    "stream_max_retries = 0",
    'query_params = { custom_option = "keep", effort = "high" }',
    "",
  ].join("\n");

describe("Caara managed Codex roles", () => {
  it.effect("regenerates marked roles while preserving existing query params", () =>
    Effect.gen(function* () {
      const root = testRoot();
      const binDir = path.join(root, "bin");
      const targetDirectory = path.join(root, "agents");
      const rolePath = path.join(targetDirectory, "caara-claude-haiku.toml");
      yield* writeExecutable({ filePath: path.join(binDir, "claude") });
      yield* writeFile({ filePath: rolePath, content: markedRoleToml() });

      const result = yield* runCaaraInstallCodexRoles({
        args: [targetDirectory],
        env: roleEnv({ home: path.join(root, "home"), pathValue: binDir }),
      });
      const { config, source } = yield* parseManagedRole({ filePath: rolePath });

      assert.strictEqual(result.exitCode, 0);
      assert.notStrictEqual(config.description, "Old generated description");
      assert.deepStrictEqual(config.model_providers.caara.query_params, {
        custom_option: "keep",
        effort: "high",
      });
      assert.match(source, /Generated by Caara/u);
    }),
  );

  it.effect("fails on unmarked same-name files without overwriting them", () =>
    Effect.gen(function* () {
      const root = testRoot();
      const binDir = path.join(root, "bin");
      const targetDirectory = path.join(root, "agents");
      const rolePath = path.join(targetDirectory, "caara-claude-haiku.toml");
      const customRole = 'name = "custom-caara-claude-haiku"\n';
      yield* writeExecutable({ filePath: path.join(binDir, "claude") });
      yield* writeFile({ filePath: rolePath, content: customRole });

      const result = yield* runCaaraInstallCodexRoles({
        args: [targetDirectory],
        env: roleEnv({ home: path.join(root, "home"), pathValue: binDir }),
      });
      const unchanged = yield* readFile({ filePath: rolePath });

      assert.strictEqual(result.exitCode, 1);
      assert.match(result.message, /unmarked existing Codex role/u);
      assert.strictEqual(unchanged, customRole);
    }),
  );

  it.effect("removes stale marked roles for drivers that are no longer available", () =>
    Effect.gen(function* () {
      const root = testRoot();
      const binDir = path.join(root, "bin");
      const targetDirectory = path.join(root, "agents");
      const staleMarked = path.join(targetDirectory, "caara-agy-gemini-3-5-flash.toml");
      const staleUnmarked = path.join(targetDirectory, "caara-agy-gpt-oss-120b.toml");
      yield* writeExecutable({ filePath: path.join(binDir, "claude") });
      yield* writeFile({ filePath: staleMarked, content: markedRoleToml() });
      yield* writeFile({ filePath: staleUnmarked, content: 'name = "custom-agy"\n' });

      const result = yield* runCaaraInstallCodexRoles({
        args: [targetDirectory],
        env: roleEnv({ home: path.join(root, "home"), pathValue: binDir }),
      });
      const markedExists = yield* pathExists({ filePath: staleMarked });
      const unmarkedExists = yield* pathExists({ filePath: staleUnmarked });

      assert.strictEqual(result.exitCode, 0);
      assert.strictEqual(markedExists, false);
      assert.strictEqual(unmarkedExists, true);
    }),
  );

  it.effect("uninstall-codex-roles removes only marked Caara roles", () =>
    Effect.gen(function* () {
      const root = testRoot();
      const targetDirectory = path.join(root, "agents");
      yield* writeFile({
        filePath: path.join(targetDirectory, "caara-claude-haiku.toml"),
        content: markedRoleToml(),
      });
      yield* writeFile({
        filePath: path.join(targetDirectory, "caara-custom.toml"),
        content: 'name = "caara-custom"\n',
      });

      const result = yield* runCaaraUninstallCodexRoles({
        args: [targetDirectory],
        env: roleEnv({ home: path.join(root, "home"), pathValue: "" }),
      });
      const filenames = yield* listFilenames({ dirPath: targetDirectory });

      assert.strictEqual(result.exitCode, 0);
      assert.deepStrictEqual(filenames, ["caara-custom.toml"]);
      assert.match(result.message, /removed 1 Codex roles/u);
    }),
  );
});
